### ISSUE TITLE
"Another scheduler is already running" when using docker-compose

### ISSUE THREAD

**Issue by ThinkTransit** [voiio/dramatiq-crontab#31]
Hi,

Great project!

When running in docker/docker-compose, shutting down the container doesn't remove the lock from the redis backend. This prevents the scheduler from running.

```
Another scheduler is already running.
```

```
  dramatiq_crontab:
    restart: unless-stopped
    platform: linux/x86_64
    image: ghcr.io/thinktransit/myproject:$VERSION
    env_file:
      - conf/dramatiq.env
      - conf/.env
    volumes:
      - ./data/web:/vol/web
    depends_on:
      - proxy
      - cache
      - app
    command: >
      sh -c "pipenv run python manage.py crontab"
```

Any ideas on how to prevent this.

Thanks
